version: '3.8'

services:
  back:
    build: ./back
    volumes:
      - ./back/src:/opt/back
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MINIO_ROOT_USER_FILE=/run/secrets/minio-user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio-password
    env_file:
      - back/.env
      - db/.env
      - minio/.env
    secrets:
      - db-password
      - minio-user
      - minio-password
    networks:
      - back_net
      - front_net
    ports:
      - '3000:3000'
    depends_on:
      - db
      - minio
    tty: true

  front:
    build: ./front
    volumes:
      - ./front:/opt/front
      - no_modules:/opt/front/node_modules
    env_file:
      - front/.env
    networks:
      - front_net
    ports:
      - '8080:8080'
    tty: true

  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    env_file:
      - db/.env
    secrets:
      - db-password
    networks:
      - back_net
    expose:
      - 3306

  minio:
    build: ./minio
    volumes:
      - ./minio/data:/data
    env_file:
      - minio/.env
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio-user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio-password
    secrets:
      - minio-user
      - minio-password
    networks:
      - back_net
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  no_modules:
secrets:
  db-password:
    file: db/password.txt
  minio-user:
    file: minio/user.txt
  minio-password:
    file: minio/password.txt
networks:
  back_net:
  front_net:
