export const RoomActionLabel = {
  CREATE_ROOM: 'ORM/ROOM/CREATE_ROOM_ACTION',
  UPSERT_ROOM: 'ORM/ROOM/UPSERT_ROOM_ACTION',
  UPSERT_ROOMS: 'ORM/ROOM/UPSERT_ROOMS_ACTION',
  GET_ROOM: 'ORM/ROOM/GET_ROOM_ACTION',
  GET_CATEGORY_ROOMS: 'ORM/ROOM/GET_CATEGORY_ROOMS_ACTION',
  GET_LATEST_ROOMS: 'ORM/ROOM/GET_LATEST_ROOMS_ACTION',
  SEARCH_ROOMS: 'ORM/ROOM/SEARCH_ROOMS_ACTION',
} as const;
