export const CategoryActionLabel = {
  CREATE_CATEGORY: 'CREATE_CATEGORY_ACTION',
  UPSERT_CATEGORIES: 'UPSERT_CATEGORIES_ACTION',
  GET_LATEST_CATEGORIES: 'GET_LATEST_CATEGORIES_ACTION',
  GET_ROOM_CATEGORIES: 'GET_ROOM_CATEGORIES_ACTION',
  UPSERT_LATEST_CATEGORIES: 'UPSERT_LATEST_CATEGORIES_ACTION',
} as const;

export const categoryJSONType = 'CategoryJSON';
