export const CategoryActionLabel = {
  CREATE_CATEGORY: 'ORM/CATEGORY/CREATE_CATEGORY_ACTION',
  UPSERT_CATEGORIES: 'ORM/CATEGORY/UPSERT_CATEGORIES_ACTION',
  GET_LATEST_CATEGORIES: 'ORM/CATEGORY/GET_LATEST_CATEGORIES_ACTION',
  GET_ROOM_CATEGORIES: 'ORM/CATEGORY/GET_ROOM_CATEGORIES_ACTION',
} as const;
