export const RoomAPIActionLabel = {
  GET_ROOM_API: 'API/ROOM/GET_ROOM_ACTION',
  GET_LATEST_ROOMS_API: 'API/ROOM/GET_LATEST_ROOMS_ACTION',
  GET_CATEGORY_ROOMS_API: 'API/ROOM/GET_CATEGORY_ROOMS_ACTION',
  SEARCH_ROOMS_API: 'API/ROOM/SEARCH_ROOMS_ACTION',
} as const;

export const RoomJSONType = 'RoomJSON';
