export const RoomActionLabel = {
  CREATE_ROOM: 'CREATE_ROOM_ACTION',
  UPSERT_ROOM: 'UPSERT_ROOM_ACTION',
  UPSERT_ROOMS: 'UPSERT_ROOMS_ACTION',
  GET_CATEGORY_ROOMS: 'GET_CATEGORY_ROOMS_ACTION',
  GET_LATEST_ROOMS: 'GET_LATEST_ROOMS_ACTION',
  UPSERT_LATEST_ROOMS: 'UPSERT_LATEST_ROOMS_ACTION'
} as const;

export const roomJSONType = 'RoomJSON';
